<?php

/**
 * Include theme.
 */
module_load_include('inc', 'civicrm_paragraph_optin', 'includes/theme');

/**
 * Include listener.
 */
module_load_include('inc', 'civicrm_paragraph_optin', 'includes/listener');

/**
 * Include admin.
 */
module_load_include('inc', 'civicrm_paragraph_optin', 'includes/admin');

/**
 * Include opt-in forms.
 */
module_load_include('inc', 'civicrm_paragraph_optin', 'includes/form_optin_anom');
module_load_include('inc', 'civicrm_paragraph_optin', 'includes/form_optin_auth');